-- Run once with delegated role-management privileges. Normal loads never use this role.
CREATE ROLE IF NOT EXISTS LIBRA_OWNER;
CREATE ROLE IF NOT EXISTS LIBRA_LOADER;
CREATE ROLE IF NOT EXISTS LIBRA_FINANCE_READER;
CREATE ROLE IF NOT EXISTS LIBRA_DQ_READER;

CREATE DATABASE IF NOT EXISTS LIBRA;
CREATE SCHEMA IF NOT EXISTS LIBRA.CONTROL;
CREATE SCHEMA IF NOT EXISTS LIBRA.LOAD;
CREATE SCHEMA IF NOT EXISTS LIBRA.CORE;
CREATE SCHEMA IF NOT EXISTS LIBRA.REPORTING;

GRANT USAGE ON DATABASE LIBRA TO ROLE LIBRA_OWNER;
GRANT USAGE ON DATABASE LIBRA TO ROLE LIBRA_LOADER;
GRANT USAGE ON DATABASE LIBRA TO ROLE LIBRA_FINANCE_READER;
GRANT USAGE ON DATABASE LIBRA TO ROLE LIBRA_DQ_READER;
GRANT USAGE ON SCHEMA LIBRA.CONTROL TO ROLE LIBRA_OWNER;
GRANT USAGE ON SCHEMA LIBRA.LOAD TO ROLE LIBRA_OWNER;
GRANT USAGE ON SCHEMA LIBRA.CORE TO ROLE LIBRA_OWNER;
GRANT USAGE ON SCHEMA LIBRA.REPORTING TO ROLE LIBRA_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA LIBRA.CONTROL TO ROLE LIBRA_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA LIBRA.LOAD TO ROLE LIBRA_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA LIBRA.CORE TO ROLE LIBRA_OWNER;
GRANT ALL PRIVILEGES ON SCHEMA LIBRA.REPORTING TO ROLE LIBRA_OWNER;

CREATE TABLE IF NOT EXISTS LIBRA.CONTROL.MIGRATION_HISTORY (
    VERSION VARCHAR(3) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    CHECKSUM VARCHAR(64) NOT NULL,
    APPLIED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT UQ_MIGRATION_VERSION UNIQUE (VERSION)
);

GRANT SELECT,INSERT ON TABLE LIBRA.CONTROL.MIGRATION_HISTORY TO ROLE LIBRA_OWNER;
