-- Money/rate columns must return only fixed-scale NUMBER metadata.
SELECT TABLE_SCHEMA,TABLE_NAME,COLUMN_NAME,DATA_TYPE,NUMERIC_PRECISION,NUMERIC_SCALE
FROM LIBRA.INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA='CORE'
  AND (
    COLUMN_NAME LIKE '%AMOUNT%'
    OR COLUMN_NAME LIKE '%EUR%'
    OR COLUMN_NAME='FX_RATE_TO_EUR'
  )
ORDER BY TABLE_NAME,ORDINAL_POSITION;

-- All natural-key duplicate counts must be zero.
SELECT 'FACT_INVOICE' TABLE_NAME,COUNT(*)-COUNT(DISTINCT INVOICE_ID) DUPLICATES
FROM LIBRA.CORE.FACT_INVOICE
UNION ALL
SELECT 'FACT_OPERATIONAL_COST',COUNT(*)-COUNT(DISTINCT COST_ID)
FROM LIBRA.CORE.FACT_OPERATIONAL_COST
UNION ALL
SELECT 'FACT_SHIPMENT',COUNT(*)-COUNT(DISTINCT SHIPMENT_ID)
FROM LIBRA.CORE.FACT_SHIPMENT;
