"""Stable public reason-code vocabulary."""

REASON_TO_RULE = {
    "DUPLICATE_INVOICE": "DUPLICATE_INVOICE",
    "MISSING_CUSTOMER_ID": "REQUIRED_IDENTIFIERS",
    "MISSING_COST_CENTER_ID": "REQUIRED_IDENTIFIERS",
    "MISSING_EXCHANGE_RATE": "EXCHANGE_RATE_EXISTS",
    "COUNTRY_VOLUME_DROP": "INVOICE_COUNTRY_VOLUME",
    "UNKNOWN_CUSTOMER_ID": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_COST_CENTER_ID": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_SHIPMENT_ID": "REFERENTIAL_INTEGRITY",
}

RULE_DATASETS = {
    "DUPLICATE_INVOICE": ("invoices",),
    "REQUIRED_IDENTIFIERS": ("shipments", "invoices", "budgets"),
    "EXCHANGE_RATE_EXISTS": ("shipments", "invoices", "budgets"),
    "INVOICE_COUNTRY_VOLUME": ("invoices",),
    "REFERENTIAL_INTEGRITY": ("shipments", "invoices", "budgets"),
}
