"""Stable public reason-code vocabulary."""

REASON_TO_RULE = {
    "DUPLICATE_INVOICE": "DUPLICATE_INVOICE",
    "CROSS_BATCH_DUPLICATE_INVOICE": "DUPLICATE_INVOICE",
    "CONFLICTING_DUPLICATE_INVOICE": "DUPLICATE_INVOICE",
    "CROSS_BATCH_DUPLICATE_RECORD": "CROSS_BATCH_RECORD_OWNERSHIP",
    "MISSING_CUSTOMER_ID": "REQUIRED_IDENTIFIERS",
    "MISSING_COST_CENTER_ID": "REQUIRED_IDENTIFIERS",
    "MISSING_ROUTE_ID": "REQUIRED_IDENTIFIERS",
    "MISSING_SHIPMENT_ID": "REQUIRED_IDENTIFIERS",
    "INVALID_FINANCIAL_VALUE": "FINITE_FINANCIAL_VALUES",
    "INVALID_SHIPMENT_VOLUME": "VALID_SHIPMENT_VOLUME",
    "INVALID_COST_TYPE": "VALID_COST_TYPE",
    "INVALID_ROUTE_DEFINITION": "REFERENTIAL_INTEGRITY",
    "INVALID_EXCHANGE_RATE": "VALID_EXCHANGE_RATES",
    "INVALID_EXCHANGE_RATE_REFERENCE": "VALID_EXCHANGE_RATES",
    "DUPLICATE_EXCHANGE_RATE": "EXCHANGE_RATE_UNIQUENESS",
    "CONFLICTING_EXCHANGE_RATE": "EXCHANGE_RATE_UNIQUENESS",
    "CONFLICTING_EXCHANGE_RATE_REFERENCE": "EXCHANGE_RATE_UNIQUENESS",
    "MISSING_EXCHANGE_RATE": "EXCHANGE_RATE_EXISTS",
    "COUNTRY_VOLUME_DROP": "INVOICE_COUNTRY_VOLUME",
    "UNKNOWN_COUNTRY_CODE": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_CURRENCY_CODE": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_CUSTOMER_ID": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_COST_CENTER_ID": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_SHIPMENT_ID": "REFERENTIAL_INTEGRITY",
    "UNKNOWN_ROUTE_ID": "REFERENTIAL_INTEGRITY",
}

RULE_DATASETS = {
    "DUPLICATE_INVOICE": ("invoices",),
    "CROSS_BATCH_RECORD_OWNERSHIP": ("shipments", "budgets", "operational_costs"),
    "REQUIRED_IDENTIFIERS": ("shipments", "invoices", "budgets", "operational_costs"),
    "FINITE_FINANCIAL_VALUES": ("shipments", "invoices", "budgets", "operational_costs"),
    "VALID_SHIPMENT_VOLUME": ("shipments",),
    "VALID_COST_TYPE": ("operational_costs",),
    "VALID_EXCHANGE_RATES": (
        "exchange_rates",
        "shipments",
        "invoices",
        "budgets",
        "operational_costs",
    ),
    "EXCHANGE_RATE_UNIQUENESS": (
        "exchange_rates",
        "shipments",
        "invoices",
        "budgets",
        "operational_costs",
    ),
    "EXCHANGE_RATE_EXISTS": ("shipments", "invoices", "budgets", "operational_costs"),
    "INVOICE_COUNTRY_VOLUME": ("invoices",),
    "REFERENTIAL_INTEGRITY": (
        "countries",
        "customers",
        "cost_centers",
        "routes",
        "exchange_rates",
        "shipments",
        "invoices",
        "budgets",
        "operational_costs",
    ),
}
