CREATE TABLE IF NOT EXISTS LIBRA.CONTROL.LOAD_RUN (
    LOAD_ID VARCHAR(64) NOT NULL,
    CONTRACT_VERSION VARCHAR(20) NOT NULL,
    SOURCE_FINGERPRINT VARCHAR(64) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    STARTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_TZ,
    ERROR_MESSAGE VARCHAR,
    CONSTRAINT PK_LOAD_RUN PRIMARY KEY (LOAD_ID),
    CONSTRAINT UQ_LOAD_FINGERPRINT UNIQUE (SOURCE_FINGERPRINT),
    CONSTRAINT CK_LOAD_STATUS CHECK (STATUS IN ('RUNNING','SUCCEEDED','FAILED'))
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CONTROL.LOAD_ITEM (
    LOAD_ID VARCHAR(64) NOT NULL,
    SOURCE_TABLE VARCHAR(100) NOT NULL,
    SOURCE_ROW_COUNT NUMBER(38,0) NOT NULL,
    SOURCE_FINANCIAL_TOTAL NUMBER(20,2),
    TARGET_ROW_COUNT NUMBER(38,0),
    TARGET_FINANCIAL_TOTAL NUMBER(20,2),
    SHA256 VARCHAR(64) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    LOADED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_LOAD_ITEM PRIMARY KEY (LOAD_ID, SOURCE_TABLE)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CONTROL.RECONCILIATION_RESULT (
    LOAD_ID VARCHAR(64) NOT NULL,
    CONTROL_NAME VARCHAR(100) NOT NULL,
    EXPECTED_VALUE NUMBER(38,2) NOT NULL,
    ACTUAL_VALUE NUMBER(38,2) NOT NULL,
    DIFFERENCE NUMBER(38,2) NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_RECON_RESULT PRIMARY KEY (LOAD_ID, CONTROL_NAME)
);
-- statement
CREATE FILE FORMAT IF NOT EXISTS LIBRA.LOAD.GOVERNED_CSV
    TYPE=CSV PARSE_HEADER=TRUE FIELD_OPTIONALLY_ENCLOSED_BY='"'
    NULL_IF=('') EMPTY_FIELD_AS_NULL=TRUE ENCODING='UTF8';
-- statement
CREATE STAGE IF NOT EXISTS LIBRA.LOAD.PACKAGE_STAGE
    DIRECTORY=(ENABLE=TRUE)
    ENCRYPTION=(TYPE='SNOWFLAKE_SSE');
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_COUNTRIES (
    COUNTRY_CODE VARCHAR, COUNTRY_NAME VARCHAR, DEFAULT_CURRENCY VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_CURRENCIES (
    CURRENCY_CODE VARCHAR, CURRENCY_NAME VARCHAR, DECIMAL_PLACES VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_CUSTOMERS (
    CUSTOMER_ID VARCHAR, CUSTOMER_NAME VARCHAR, COUNTRY_CODE VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_COST_CENTERS (
    COST_CENTER_ID VARCHAR, COST_CENTER_NAME VARCHAR, COUNTRY_CODE VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_ROUTES (
    ROUTE_ID VARCHAR, ORIGIN_COUNTRY_CODE VARCHAR, DESTINATION_COUNTRY_CODE VARCHAR,
    TRANSPORT_MODE VARCHAR, DISTANCE_KM VARCHAR, STANDARD_TRANSIT_DAYS VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_SHIPMENTS (
    SHIPMENT_ID VARCHAR, SHIPMENT_DATE VARCHAR, ROUTE_ID VARCHAR, VOLUME_M3 VARCHAR,
    COUNTRY_CODE VARCHAR, CUSTOMER_ID VARCHAR, COST_CENTER_ID VARCHAR,
    CURRENCY_CODE VARCHAR, REVENUE_AMOUNT VARCHAR, FX_RATE_TO_EUR VARCHAR,
    AMOUNT_EUR VARCHAR, _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR,
    _SOURCE_FILE VARCHAR, _SOURCE_ROW_NUMBER VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_INVOICES (
    INVOICE_ID VARCHAR, SHIPMENT_ID VARCHAR, INVOICE_DATE VARCHAR, COUNTRY_CODE VARCHAR,
    CUSTOMER_ID VARCHAR, COST_CENTER_ID VARCHAR, CURRENCY_CODE VARCHAR,
    REVENUE_AMOUNT VARCHAR, FX_RATE_TO_EUR VARCHAR, AMOUNT_EUR VARCHAR,
    AMOUNT_AT_COMPARISON_RATE_EUR VARCHAR, SOURCE_UPDATED_AT VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR, _SOURCE_FILE VARCHAR,
    _SOURCE_ROW_NUMBER VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_OPERATIONAL_COSTS (
    COST_ID VARCHAR, SHIPMENT_ID VARCHAR, ROUTE_ID VARCHAR, COST_CENTER_ID VARCHAR,
    COUNTRY_CODE VARCHAR, POSTING_DATE VARCHAR, COST_TYPE VARCHAR, AMOUNT VARCHAR,
    CURRENCY_CODE VARCHAR, FX_RATE_TO_EUR VARCHAR, AMOUNT_EUR VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR, _SOURCE_FILE VARCHAR,
    _SOURCE_ROW_NUMBER VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_BUDGETS (
    MONTH_START VARCHAR, COST_CENTER_ID VARCHAR, CURRENCY_CODE VARCHAR,
    BUDGET_AMOUNT VARCHAR, FX_RATE_TO_EUR VARCHAR, AMOUNT_EUR VARCHAR,
    _BATCH_ID VARCHAR, _SOURCE_FINGERPRINT VARCHAR, _SOURCE_FILE VARCHAR,
    _SOURCE_ROW_NUMBER VARCHAR
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.LOAD.STG_DATA_QUALITY_RESULTS (
    BATCH_ID VARCHAR, AFFECTED_DATASET VARCHAR, RULE_NAME VARCHAR,
    VALIDATION_STATUS VARCHAR, FAILURE_REASON VARCHAR, FAILED_ROW_COUNT VARCHAR,
    AFFECTED_FINANCIAL_AMOUNT_EUR VARCHAR, EXECUTION_TIMESTAMP VARCHAR,
    LATEST_SUCCESSFUL_REFRESH_TIMESTAMP VARCHAR, _SOURCE_FINGERPRINT VARCHAR
);
