CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_DATE (
    DATE_KEY NUMBER(8,0) NOT NULL, DATE_VALUE DATE NOT NULL, YEAR_NUMBER NUMBER(4,0) NOT NULL,
    QUARTER_NUMBER NUMBER(1,0) NOT NULL, MONTH_NUMBER NUMBER(2,0) NOT NULL,
    MONTH_NAME VARCHAR(20) NOT NULL, MONTH_START DATE NOT NULL,
    CONSTRAINT PK_DIM_DATE PRIMARY KEY (DATE_KEY), CONSTRAINT UQ_DIM_DATE UNIQUE (DATE_VALUE)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_COUNTRY (
    COUNTRY_KEY NUMBER AUTOINCREMENT, COUNTRY_CODE VARCHAR(10) NOT NULL,
    COUNTRY_NAME VARCHAR(200) NOT NULL, DEFAULT_CURRENCY VARCHAR(10) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DIM_COUNTRY PRIMARY KEY (COUNTRY_KEY),
    CONSTRAINT UQ_DIM_COUNTRY UNIQUE (COUNTRY_CODE)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_CURRENCY (
    CURRENCY_KEY NUMBER AUTOINCREMENT, CURRENCY_CODE VARCHAR(10) NOT NULL,
    CURRENCY_NAME VARCHAR(100) NOT NULL, DECIMAL_PLACES NUMBER(2,0) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DIM_CURRENCY PRIMARY KEY (CURRENCY_KEY),
    CONSTRAINT UQ_DIM_CURRENCY UNIQUE (CURRENCY_CODE)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_CUSTOMER (
    CUSTOMER_KEY NUMBER AUTOINCREMENT, CUSTOMER_ID VARCHAR(100) NOT NULL,
    CUSTOMER_NAME VARCHAR(200) NOT NULL, COUNTRY_KEY NUMBER NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_KEY),
    CONSTRAINT UQ_DIM_CUSTOMER UNIQUE (CUSTOMER_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_COST_CENTER (
    COST_CENTER_KEY NUMBER AUTOINCREMENT, COST_CENTER_ID VARCHAR(100) NOT NULL,
    COST_CENTER_NAME VARCHAR(200) NOT NULL, COUNTRY_KEY NUMBER NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DIM_COST_CENTER PRIMARY KEY (COST_CENTER_KEY),
    CONSTRAINT UQ_DIM_COST_CENTER UNIQUE (COST_CENTER_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.DIM_ROUTE (
    ROUTE_KEY NUMBER AUTOINCREMENT, ROUTE_ID VARCHAR(100) NOT NULL,
    ORIGIN_COUNTRY_KEY NUMBER NOT NULL, DESTINATION_COUNTRY_KEY NUMBER NOT NULL,
    TRANSPORT_MODE VARCHAR(40) NOT NULL, DISTANCE_KM NUMBER(20,2) NOT NULL,
    STANDARD_TRANSIT_DAYS NUMBER(10,0) NOT NULL, SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    CONSTRAINT PK_DIM_ROUTE PRIMARY KEY (ROUTE_KEY), CONSTRAINT UQ_DIM_ROUTE UNIQUE (ROUTE_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.FACT_SHIPMENT (
    SHIPMENT_ID VARCHAR(100) NOT NULL, SHIPMENT_DATE_KEY NUMBER(8,0) NOT NULL,
    ROUTE_KEY NUMBER NOT NULL, COUNTRY_KEY NUMBER NOT NULL, CUSTOMER_KEY NUMBER NOT NULL,
    COST_CENTER_KEY NUMBER NOT NULL, CURRENCY_KEY NUMBER NOT NULL,
    VOLUME_M3 NUMBER(20,2) NOT NULL, ORIGINAL_AMOUNT NUMBER(20,2) NOT NULL,
    FX_RATE_TO_EUR NUMBER(18,6) NOT NULL, AMOUNT_EUR NUMBER(20,2) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL, SOURCE_FINGERPRINT VARCHAR(64) NOT NULL,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0),
    CONSTRAINT PK_FACT_SHIPMENT PRIMARY KEY (SHIPMENT_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.FACT_INVOICE (
    INVOICE_ID VARCHAR(100) NOT NULL, SHIPMENT_ID VARCHAR(100) NOT NULL,
    INVOICE_DATE_KEY NUMBER(8,0) NOT NULL, ROUTE_KEY NUMBER NOT NULL, COUNTRY_KEY NUMBER NOT NULL,
    CUSTOMER_KEY NUMBER NOT NULL, COST_CENTER_KEY NUMBER NOT NULL, CURRENCY_KEY NUMBER NOT NULL,
    ORIGINAL_AMOUNT NUMBER(20,2) NOT NULL, FX_RATE_TO_EUR NUMBER(18,6) NOT NULL,
    AMOUNT_EUR NUMBER(20,2) NOT NULL, AMOUNT_AT_COMPARISON_RATE_EUR NUMBER(20,2) NOT NULL,
    SOURCE_UPDATED_AT TIMESTAMP_NTZ, SOURCE_BATCH_ID VARCHAR(64) NOT NULL,
    SOURCE_FINGERPRINT VARCHAR(64) NOT NULL, SOURCE_FILE VARCHAR,
    SOURCE_ROW_NUMBER NUMBER(38,0), CONSTRAINT PK_FACT_INVOICE PRIMARY KEY (INVOICE_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.FACT_OPERATIONAL_COST (
    COST_ID VARCHAR(100) NOT NULL, SHIPMENT_ID VARCHAR(100) NOT NULL,
    ROUTE_KEY NUMBER NOT NULL, CUSTOMER_KEY NUMBER NOT NULL, COST_CENTER_KEY NUMBER NOT NULL,
    COUNTRY_KEY NUMBER NOT NULL,
    POSTING_DATE_KEY NUMBER(8,0) NOT NULL, COST_TYPE VARCHAR(40) NOT NULL,
    CURRENCY_KEY NUMBER NOT NULL, ORIGINAL_AMOUNT NUMBER(20,2) NOT NULL,
    FX_RATE_TO_EUR NUMBER(18,6) NOT NULL, AMOUNT_EUR NUMBER(20,2) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL, SOURCE_FINGERPRINT VARCHAR(64) NOT NULL,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0),
    CONSTRAINT PK_FACT_OPERATIONAL_COST PRIMARY KEY (COST_ID)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.FACT_BUDGET (
    MONTH_DATE_KEY NUMBER(8,0) NOT NULL, COST_CENTER_KEY NUMBER NOT NULL,
    CURRENCY_KEY NUMBER NOT NULL, ORIGINAL_AMOUNT NUMBER(20,2) NOT NULL,
    FX_RATE_TO_EUR NUMBER(18,6) NOT NULL, AMOUNT_EUR NUMBER(20,2) NOT NULL,
    SOURCE_BATCH_ID VARCHAR(64) NOT NULL, SOURCE_FINGERPRINT VARCHAR(64) NOT NULL,
    SOURCE_FILE VARCHAR, SOURCE_ROW_NUMBER NUMBER(38,0),
    CONSTRAINT PK_FACT_BUDGET PRIMARY KEY (MONTH_DATE_KEY, COST_CENTER_KEY)
);
-- statement
CREATE TABLE IF NOT EXISTS LIBRA.CORE.FACT_DATA_QUALITY_RESULT (
    BATCH_ID VARCHAR(64) NOT NULL, EXECUTION_DATE_KEY NUMBER(8,0) NOT NULL,
    AFFECTED_DATASET VARCHAR(100) NOT NULL, RULE_NAME VARCHAR(100) NOT NULL,
    VALIDATION_STATUS VARCHAR(10) NOT NULL, FAILURE_REASON VARCHAR,
    FAILED_ROW_COUNT NUMBER(38,0) NOT NULL, AFFECTED_FINANCIAL_AMOUNT_EUR NUMBER(20,2),
    EXECUTION_TIMESTAMP TIMESTAMP_TZ NOT NULL, LATEST_SUCCESSFUL_REFRESH_TIMESTAMP TIMESTAMP_TZ,
    SOURCE_FINGERPRINT VARCHAR(64) NOT NULL,
    CONSTRAINT PK_FACT_DQ PRIMARY KEY (BATCH_ID, AFFECTED_DATASET, RULE_NAME)
);
-- statement
CREATE OR REPLACE PROCEDURE LIBRA.CONTROL.PUBLISH_STAGED_PACKAGE(P_LOAD_ID VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS
$$
BEGIN
    MERGE INTO LIBRA.CORE.DIM_COUNTRY T USING LIBRA.LOAD.STG_COUNTRIES S
      ON T.COUNTRY_CODE=S.COUNTRY_CODE
    WHEN MATCHED THEN UPDATE SET COUNTRY_NAME=S.COUNTRY_NAME,
      DEFAULT_CURRENCY=S.DEFAULT_CURRENCY,SOURCE_BATCH_ID=S._BATCH_ID
    WHEN NOT MATCHED THEN INSERT(COUNTRY_CODE,COUNTRY_NAME,DEFAULT_CURRENCY,SOURCE_BATCH_ID)
      VALUES(S.COUNTRY_CODE,S.COUNTRY_NAME,S.DEFAULT_CURRENCY,S._BATCH_ID);

    MERGE INTO LIBRA.CORE.DIM_CURRENCY T USING LIBRA.LOAD.STG_CURRENCIES S
      ON T.CURRENCY_CODE=S.CURRENCY_CODE
    WHEN MATCHED THEN UPDATE SET CURRENCY_NAME=S.CURRENCY_NAME,
      DECIMAL_PLACES=S.DECIMAL_PLACES::NUMBER,SOURCE_BATCH_ID=S._BATCH_ID
    WHEN NOT MATCHED THEN INSERT(CURRENCY_CODE,CURRENCY_NAME,DECIMAL_PLACES,SOURCE_BATCH_ID)
      VALUES(S.CURRENCY_CODE,S.CURRENCY_NAME,S.DECIMAL_PLACES::NUMBER,S._BATCH_ID);

    MERGE INTO LIBRA.CORE.DIM_CUSTOMER T USING (
      SELECT S.*,C.COUNTRY_KEY FROM LIBRA.LOAD.STG_CUSTOMERS S
      JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_CODE)
    ) S ON T.CUSTOMER_ID=S.CUSTOMER_ID
    WHEN MATCHED THEN UPDATE SET CUSTOMER_NAME=S.CUSTOMER_NAME,
      COUNTRY_KEY=S.COUNTRY_KEY,SOURCE_BATCH_ID=S._BATCH_ID
    WHEN NOT MATCHED THEN INSERT(CUSTOMER_ID,CUSTOMER_NAME,COUNTRY_KEY,SOURCE_BATCH_ID)
      VALUES(S.CUSTOMER_ID,S.CUSTOMER_NAME,S.COUNTRY_KEY,S._BATCH_ID);

    MERGE INTO LIBRA.CORE.DIM_COST_CENTER T USING (
      SELECT S.*,C.COUNTRY_KEY FROM LIBRA.LOAD.STG_COST_CENTERS S
      JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_CODE)
    ) S ON T.COST_CENTER_ID=S.COST_CENTER_ID
    WHEN MATCHED THEN UPDATE SET COST_CENTER_NAME=S.COST_CENTER_NAME,
      COUNTRY_KEY=S.COUNTRY_KEY,SOURCE_BATCH_ID=S._BATCH_ID
    WHEN NOT MATCHED THEN INSERT(COST_CENTER_ID,COST_CENTER_NAME,COUNTRY_KEY,SOURCE_BATCH_ID)
      VALUES(S.COST_CENTER_ID,S.COST_CENTER_NAME,S.COUNTRY_KEY,S._BATCH_ID);

    MERGE INTO LIBRA.CORE.DIM_ROUTE T USING (
      SELECT S.*,O.COUNTRY_KEY ORIGIN_COUNTRY_KEY,D.COUNTRY_KEY DESTINATION_COUNTRY_KEY
      FROM LIBRA.LOAD.STG_ROUTES S
      JOIN LIBRA.CORE.DIM_COUNTRY O ON O.COUNTRY_CODE=S.ORIGIN_COUNTRY_CODE
      JOIN LIBRA.CORE.DIM_COUNTRY D ON D.COUNTRY_CODE=S.DESTINATION_COUNTRY_CODE
    ) S ON T.ROUTE_ID=S.ROUTE_ID
    WHEN MATCHED THEN UPDATE SET ORIGIN_COUNTRY_KEY=S.ORIGIN_COUNTRY_KEY,
      DESTINATION_COUNTRY_KEY=S.DESTINATION_COUNTRY_KEY,TRANSPORT_MODE=S.TRANSPORT_MODE,
      DISTANCE_KM=S.DISTANCE_KM::NUMBER(20,2),
      STANDARD_TRANSIT_DAYS=S.STANDARD_TRANSIT_DAYS::NUMBER,SOURCE_BATCH_ID=S._BATCH_ID
    WHEN NOT MATCHED THEN INSERT(ROUTE_ID,ORIGIN_COUNTRY_KEY,DESTINATION_COUNTRY_KEY,
      TRANSPORT_MODE,DISTANCE_KM,STANDARD_TRANSIT_DAYS,SOURCE_BATCH_ID)
      VALUES(S.ROUTE_ID,S.ORIGIN_COUNTRY_KEY,S.DESTINATION_COUNTRY_KEY,S.TRANSPORT_MODE,
      S.DISTANCE_KM::NUMBER(20,2),S.STANDARD_TRANSIT_DAYS::NUMBER,S._BATCH_ID);

    INSERT INTO LIBRA.CORE.DIM_DATE
      (DATE_KEY,DATE_VALUE,YEAR_NUMBER,QUARTER_NUMBER,MONTH_NUMBER,MONTH_NAME,MONTH_START)
    SELECT TO_NUMBER(TO_CHAR(DATE_VALUE,'YYYYMMDD')),DATE_VALUE,YEAR(DATE_VALUE),
      QUARTER(DATE_VALUE),MONTH(DATE_VALUE),MONTHNAME(DATE_VALUE),DATE_TRUNC('MONTH',DATE_VALUE)
    FROM (
      SELECT DISTINCT TO_DATE(SHIPMENT_DATE) DATE_VALUE FROM LIBRA.LOAD.STG_SHIPMENTS
      UNION SELECT DISTINCT TO_DATE(INVOICE_DATE) FROM LIBRA.LOAD.STG_INVOICES
      UNION SELECT DISTINCT TO_DATE(POSTING_DATE) FROM LIBRA.LOAD.STG_OPERATIONAL_COSTS
      UNION SELECT DISTINCT TO_DATE(MONTH_START) FROM LIBRA.LOAD.STG_BUDGETS
      UNION SELECT DISTINCT TO_DATE(EXECUTION_TIMESTAMP) FROM LIBRA.LOAD.STG_DATA_QUALITY_RESULTS
    ) S WHERE NOT EXISTS (
      SELECT 1 FROM LIBRA.CORE.DIM_DATE D WHERE D.DATE_VALUE=S.DATE_VALUE
    );

    MERGE INTO LIBRA.CORE.FACT_SHIPMENT T USING (
      SELECT S.*,TO_NUMBER(TO_CHAR(TO_DATE(S.SHIPMENT_DATE),'YYYYMMDD')) SHIPMENT_DATE_KEY,
        R.ROUTE_KEY,C.COUNTRY_KEY,CU.CUSTOMER_KEY,CC.COST_CENTER_KEY,CY.CURRENCY_KEY
      FROM LIBRA.LOAD.STG_SHIPMENTS S
      JOIN LIBRA.CORE.DIM_ROUTE R USING(ROUTE_ID)
      JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_CODE)
      JOIN LIBRA.CORE.DIM_CUSTOMER CU USING(CUSTOMER_ID)
      JOIN LIBRA.CORE.DIM_COST_CENTER CC USING(COST_CENTER_ID)
      JOIN LIBRA.CORE.DIM_CURRENCY CY USING(CURRENCY_CODE)
    ) S ON T.SHIPMENT_ID=S.SHIPMENT_ID
    WHEN MATCHED THEN UPDATE SET SHIPMENT_DATE_KEY=S.SHIPMENT_DATE_KEY,
      ROUTE_KEY=S.ROUTE_KEY,COUNTRY_KEY=S.COUNTRY_KEY,CUSTOMER_KEY=S.CUSTOMER_KEY,
      COST_CENTER_KEY=S.COST_CENTER_KEY,CURRENCY_KEY=S.CURRENCY_KEY,
      VOLUME_M3=S.VOLUME_M3::NUMBER(20,2),ORIGINAL_AMOUNT=S.REVENUE_AMOUNT::NUMBER(20,2),
      FX_RATE_TO_EUR=S.FX_RATE_TO_EUR::NUMBER(18,6),AMOUNT_EUR=S.AMOUNT_EUR::NUMBER(20,2),
      SOURCE_BATCH_ID=S._BATCH_ID,SOURCE_FINGERPRINT=S._SOURCE_FINGERPRINT,
      SOURCE_FILE=S._SOURCE_FILE,SOURCE_ROW_NUMBER=S._SOURCE_ROW_NUMBER::NUMBER
    WHEN NOT MATCHED THEN INSERT(SHIPMENT_ID,SHIPMENT_DATE_KEY,ROUTE_KEY,COUNTRY_KEY,
      CUSTOMER_KEY,COST_CENTER_KEY,CURRENCY_KEY,VOLUME_M3,ORIGINAL_AMOUNT,FX_RATE_TO_EUR,
      AMOUNT_EUR,SOURCE_BATCH_ID,SOURCE_FINGERPRINT,SOURCE_FILE,SOURCE_ROW_NUMBER)
      VALUES(S.SHIPMENT_ID,S.SHIPMENT_DATE_KEY,S.ROUTE_KEY,S.COUNTRY_KEY,S.CUSTOMER_KEY,
      S.COST_CENTER_KEY,S.CURRENCY_KEY,S.VOLUME_M3::NUMBER(20,2),
      S.REVENUE_AMOUNT::NUMBER(20,2),S.FX_RATE_TO_EUR::NUMBER(18,6),
      S.AMOUNT_EUR::NUMBER(20,2),S._BATCH_ID,S._SOURCE_FINGERPRINT,S._SOURCE_FILE,
      S._SOURCE_ROW_NUMBER::NUMBER);

    MERGE INTO LIBRA.CORE.FACT_INVOICE T USING (
      SELECT S.*,TO_NUMBER(TO_CHAR(TO_DATE(S.INVOICE_DATE),'YYYYMMDD')) INVOICE_DATE_KEY,
        FS.ROUTE_KEY,C.COUNTRY_KEY,CU.CUSTOMER_KEY,CC.COST_CENTER_KEY,CY.CURRENCY_KEY
      FROM LIBRA.LOAD.STG_INVOICES S
      JOIN LIBRA.CORE.FACT_SHIPMENT FS USING(SHIPMENT_ID)
      JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_CODE)
      JOIN LIBRA.CORE.DIM_CUSTOMER CU USING(CUSTOMER_ID)
      JOIN LIBRA.CORE.DIM_COST_CENTER CC USING(COST_CENTER_ID)
      JOIN LIBRA.CORE.DIM_CURRENCY CY USING(CURRENCY_CODE)
    ) S ON T.INVOICE_ID=S.INVOICE_ID
    WHEN MATCHED THEN UPDATE SET SHIPMENT_ID=S.SHIPMENT_ID,
      INVOICE_DATE_KEY=S.INVOICE_DATE_KEY,ROUTE_KEY=S.ROUTE_KEY,COUNTRY_KEY=S.COUNTRY_KEY,
      CUSTOMER_KEY=S.CUSTOMER_KEY,COST_CENTER_KEY=S.COST_CENTER_KEY,CURRENCY_KEY=S.CURRENCY_KEY,
      ORIGINAL_AMOUNT=S.REVENUE_AMOUNT::NUMBER(20,2),
      FX_RATE_TO_EUR=S.FX_RATE_TO_EUR::NUMBER(18,6),AMOUNT_EUR=S.AMOUNT_EUR::NUMBER(20,2),
      AMOUNT_AT_COMPARISON_RATE_EUR=S.AMOUNT_AT_COMPARISON_RATE_EUR::NUMBER(20,2),
      SOURCE_UPDATED_AT=S.SOURCE_UPDATED_AT::TIMESTAMP_NTZ,SOURCE_BATCH_ID=S._BATCH_ID,
      SOURCE_FINGERPRINT=S._SOURCE_FINGERPRINT,SOURCE_FILE=S._SOURCE_FILE,
      SOURCE_ROW_NUMBER=S._SOURCE_ROW_NUMBER::NUMBER
    WHEN NOT MATCHED THEN INSERT(INVOICE_ID,SHIPMENT_ID,INVOICE_DATE_KEY,ROUTE_KEY,COUNTRY_KEY,
      CUSTOMER_KEY,COST_CENTER_KEY,CURRENCY_KEY,ORIGINAL_AMOUNT,FX_RATE_TO_EUR,AMOUNT_EUR,
      AMOUNT_AT_COMPARISON_RATE_EUR,SOURCE_UPDATED_AT,SOURCE_BATCH_ID,SOURCE_FINGERPRINT,
      SOURCE_FILE,SOURCE_ROW_NUMBER)
      VALUES(S.INVOICE_ID,S.SHIPMENT_ID,S.INVOICE_DATE_KEY,S.ROUTE_KEY,S.COUNTRY_KEY,S.CUSTOMER_KEY,
      S.COST_CENTER_KEY,S.CURRENCY_KEY,S.REVENUE_AMOUNT::NUMBER(20,2),
      S.FX_RATE_TO_EUR::NUMBER(18,6),S.AMOUNT_EUR::NUMBER(20,2),
      S.AMOUNT_AT_COMPARISON_RATE_EUR::NUMBER(20,2),S.SOURCE_UPDATED_AT::TIMESTAMP_NTZ,
      S._BATCH_ID,S._SOURCE_FINGERPRINT,S._SOURCE_FILE,S._SOURCE_ROW_NUMBER::NUMBER);

    MERGE INTO LIBRA.CORE.FACT_OPERATIONAL_COST T USING (
      SELECT S.*,TO_NUMBER(TO_CHAR(TO_DATE(S.POSTING_DATE),'YYYYMMDD')) POSTING_DATE_KEY,
        R.ROUTE_KEY,FS.CUSTOMER_KEY,CC.COST_CENTER_KEY,C.COUNTRY_KEY,CY.CURRENCY_KEY
      FROM LIBRA.LOAD.STG_OPERATIONAL_COSTS S
      JOIN LIBRA.CORE.FACT_SHIPMENT FS USING(SHIPMENT_ID)
      JOIN LIBRA.CORE.DIM_ROUTE R USING(ROUTE_ID)
      JOIN LIBRA.CORE.DIM_COST_CENTER CC USING(COST_CENTER_ID)
      JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_CODE)
      JOIN LIBRA.CORE.DIM_CURRENCY CY USING(CURRENCY_CODE)
    ) S ON T.COST_ID=S.COST_ID
    WHEN MATCHED THEN UPDATE SET SHIPMENT_ID=S.SHIPMENT_ID,ROUTE_KEY=S.ROUTE_KEY,
      CUSTOMER_KEY=S.CUSTOMER_KEY,COST_CENTER_KEY=S.COST_CENTER_KEY,
      COUNTRY_KEY=S.COUNTRY_KEY,POSTING_DATE_KEY=S.POSTING_DATE_KEY,COST_TYPE=S.COST_TYPE,
      CURRENCY_KEY=S.CURRENCY_KEY,ORIGINAL_AMOUNT=S.AMOUNT::NUMBER(20,2),
      FX_RATE_TO_EUR=S.FX_RATE_TO_EUR::NUMBER(18,6),AMOUNT_EUR=S.AMOUNT_EUR::NUMBER(20,2),
      SOURCE_BATCH_ID=S._BATCH_ID,SOURCE_FINGERPRINT=S._SOURCE_FINGERPRINT,
      SOURCE_FILE=S._SOURCE_FILE,SOURCE_ROW_NUMBER=S._SOURCE_ROW_NUMBER::NUMBER
    WHEN NOT MATCHED THEN INSERT(COST_ID,SHIPMENT_ID,ROUTE_KEY,CUSTOMER_KEY,COST_CENTER_KEY,
      COUNTRY_KEY,
      POSTING_DATE_KEY,COST_TYPE,CURRENCY_KEY,ORIGINAL_AMOUNT,FX_RATE_TO_EUR,AMOUNT_EUR,
      SOURCE_BATCH_ID,SOURCE_FINGERPRINT,SOURCE_FILE,SOURCE_ROW_NUMBER)
      VALUES(S.COST_ID,S.SHIPMENT_ID,S.ROUTE_KEY,S.CUSTOMER_KEY,S.COST_CENTER_KEY,S.COUNTRY_KEY,
      S.POSTING_DATE_KEY,S.COST_TYPE,S.CURRENCY_KEY,S.AMOUNT::NUMBER(20,2),
      S.FX_RATE_TO_EUR::NUMBER(18,6),S.AMOUNT_EUR::NUMBER(20,2),S._BATCH_ID,
      S._SOURCE_FINGERPRINT,S._SOURCE_FILE,S._SOURCE_ROW_NUMBER::NUMBER);

    MERGE INTO LIBRA.CORE.FACT_BUDGET T USING (
      SELECT S.*,TO_NUMBER(TO_CHAR(TO_DATE(S.MONTH_START),'YYYYMMDD')) MONTH_DATE_KEY,
        CC.COST_CENTER_KEY,CY.CURRENCY_KEY
      FROM LIBRA.LOAD.STG_BUDGETS S
      JOIN LIBRA.CORE.DIM_COST_CENTER CC USING(COST_CENTER_ID)
      JOIN LIBRA.CORE.DIM_CURRENCY CY USING(CURRENCY_CODE)
    ) S ON T.MONTH_DATE_KEY=S.MONTH_DATE_KEY AND T.COST_CENTER_KEY=S.COST_CENTER_KEY
    WHEN MATCHED THEN UPDATE SET CURRENCY_KEY=S.CURRENCY_KEY,
      ORIGINAL_AMOUNT=S.BUDGET_AMOUNT::NUMBER(20,2),
      FX_RATE_TO_EUR=S.FX_RATE_TO_EUR::NUMBER(18,6),AMOUNT_EUR=S.AMOUNT_EUR::NUMBER(20,2),
      SOURCE_BATCH_ID=S._BATCH_ID,SOURCE_FINGERPRINT=S._SOURCE_FINGERPRINT,
      SOURCE_FILE=S._SOURCE_FILE,SOURCE_ROW_NUMBER=S._SOURCE_ROW_NUMBER::NUMBER
    WHEN NOT MATCHED THEN INSERT(MONTH_DATE_KEY,COST_CENTER_KEY,CURRENCY_KEY,ORIGINAL_AMOUNT,
      FX_RATE_TO_EUR,AMOUNT_EUR,SOURCE_BATCH_ID,SOURCE_FINGERPRINT,SOURCE_FILE,SOURCE_ROW_NUMBER)
      VALUES(S.MONTH_DATE_KEY,S.COST_CENTER_KEY,S.CURRENCY_KEY,
      S.BUDGET_AMOUNT::NUMBER(20,2),S.FX_RATE_TO_EUR::NUMBER(18,6),
      S.AMOUNT_EUR::NUMBER(20,2),S._BATCH_ID,S._SOURCE_FINGERPRINT,S._SOURCE_FILE,
      S._SOURCE_ROW_NUMBER::NUMBER);

    MERGE INTO LIBRA.CORE.FACT_DATA_QUALITY_RESULT T USING (
      SELECT S.*,TO_NUMBER(TO_CHAR(TO_DATE(S.EXECUTION_TIMESTAMP),'YYYYMMDD')) EXECUTION_DATE_KEY
      FROM LIBRA.LOAD.STG_DATA_QUALITY_RESULTS S
    ) S ON T.BATCH_ID=S.BATCH_ID AND T.AFFECTED_DATASET=S.AFFECTED_DATASET
      AND T.RULE_NAME=S.RULE_NAME
    WHEN MATCHED THEN UPDATE SET VALIDATION_STATUS=S.VALIDATION_STATUS,
      FAILURE_REASON=S.FAILURE_REASON,FAILED_ROW_COUNT=S.FAILED_ROW_COUNT::NUMBER,
      AFFECTED_FINANCIAL_AMOUNT_EUR=S.AFFECTED_FINANCIAL_AMOUNT_EUR::NUMBER(20,2),
      EXECUTION_TIMESTAMP=S.EXECUTION_TIMESTAMP::TIMESTAMP_TZ,
      LATEST_SUCCESSFUL_REFRESH_TIMESTAMP=S.LATEST_SUCCESSFUL_REFRESH_TIMESTAMP::TIMESTAMP_TZ
    WHEN NOT MATCHED THEN INSERT(BATCH_ID,EXECUTION_DATE_KEY,AFFECTED_DATASET,RULE_NAME,
      VALIDATION_STATUS,FAILURE_REASON,FAILED_ROW_COUNT,AFFECTED_FINANCIAL_AMOUNT_EUR,
      EXECUTION_TIMESTAMP,LATEST_SUCCESSFUL_REFRESH_TIMESTAMP,SOURCE_FINGERPRINT)
      VALUES(S.BATCH_ID,S.EXECUTION_DATE_KEY,S.AFFECTED_DATASET,S.RULE_NAME,
      S.VALIDATION_STATUS,S.FAILURE_REASON,S.FAILED_ROW_COUNT::NUMBER,
      S.AFFECTED_FINANCIAL_AMOUNT_EUR::NUMBER(20,2),S.EXECUTION_TIMESTAMP::TIMESTAMP_TZ,
      S.LATEST_SUCCESSFUL_REFRESH_TIMESTAMP::TIMESTAMP_TZ,S._SOURCE_FINGERPRINT);

    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.FACT_INVOICE),
      TARGET_FINANCIAL_TOTAL=(SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_INVOICE),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='invoices';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET
      TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.FACT_OPERATIONAL_COST),
      TARGET_FINANCIAL_TOTAL=(SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_OPERATIONAL_COST),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='operational_costs';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.FACT_BUDGET),
      TARGET_FINANCIAL_TOTAL=(SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_BUDGET),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='budgets';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.FACT_SHIPMENT),
      TARGET_FINANCIAL_TOTAL=(SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_SHIPMENT),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='shipments';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.DIM_COUNTRY),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='countries';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.DIM_CURRENCY),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='currencies';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.DIM_CUSTOMER),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='customers';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET
      TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.DIM_COST_CENTER),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='cost_centers';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.DIM_ROUTE),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='routes';
    UPDATE LIBRA.CONTROL.LOAD_ITEM SET
      TARGET_ROW_COUNT=(SELECT COUNT(*) FROM LIBRA.CORE.FACT_DATA_QUALITY_RESULT),
      STATUS='PUBLISHED' WHERE LOAD_ID=:P_LOAD_ID AND SOURCE_TABLE='data_quality_results';

    DELETE FROM LIBRA.CONTROL.RECONCILIATION_RESULT WHERE LOAD_ID=:P_LOAD_ID;
    INSERT INTO LIBRA.CONTROL.RECONCILIATION_RESULT
      (LOAD_ID,CONTROL_NAME,EXPECTED_VALUE,ACTUAL_VALUE,DIFFERENCE,STATUS)
    WITH ACTUAL AS (
      SELECT 'invoice_count' CONTROL_NAME,COUNT(*)::NUMBER(38,2) ACTUAL_VALUE
        FROM LIBRA.CORE.FACT_INVOICE
      UNION ALL SELECT 'operational_cost_count',COUNT(*) FROM LIBRA.CORE.FACT_OPERATIONAL_COST
      UNION ALL SELECT 'revenue_eur',SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_INVOICE
      UNION ALL SELECT 'operational_cost_eur',SUM(AMOUNT_EUR)
        FROM LIBRA.CORE.FACT_OPERATIONAL_COST
      UNION ALL SELECT 'gross_profit_eur',
        (SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_INVOICE)
        -(SELECT SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_OPERATIONAL_COST)
      UNION ALL SELECT 'budget_eur',SUM(AMOUNT_EUR) FROM LIBRA.CORE.FACT_BUDGET
      UNION ALL SELECT 'monthly_country_finance_count',COUNT(*)
        FROM LIBRA.REPORTING.MONTHLY_COUNTRY_FINANCE
      UNION ALL SELECT 'route_profitability_count',COUNT(*)
        FROM LIBRA.REPORTING.ROUTE_PROFITABILITY
      UNION ALL SELECT 'customer_profitability_count',COUNT(*)
        FROM LIBRA.REPORTING.CUSTOMER_PROFITABILITY
      UNION ALL SELECT 'budget_vs_actual_count',COUNT(*) FROM LIBRA.REPORTING.BUDGET_VS_ACTUAL
      UNION ALL SELECT 'healthy_data_quality_count',COUNT(*)
        FROM LIBRA.CORE.FACT_DATA_QUALITY_RESULT WHERE BATCH_ID='slice001-healthy'
      UNION ALL SELECT 'retained_data_quality_count',COUNT(*)
        FROM LIBRA.CORE.FACT_DATA_QUALITY_RESULT
      UNION ALL SELECT 'duplicate_invoice_ids',COUNT(*)-COUNT(DISTINCT INVOICE_ID)
        FROM LIBRA.CORE.FACT_INVOICE
      UNION ALL SELECT 'duplicate_cost_ids',COUNT(*)-COUNT(DISTINCT COST_ID)
        FROM LIBRA.CORE.FACT_OPERATIONAL_COST
      UNION ALL SELECT 'duplicate_shipment_ids',COUNT(*)-COUNT(DISTINCT SHIPMENT_ID)
        FROM LIBRA.CORE.FACT_SHIPMENT
    ), EXPECTED AS (
      SELECT COLUMN1 CONTROL_NAME,COLUMN2::NUMBER(38,2) EXPECTED_VALUE FROM VALUES
        ('invoice_count',720),('operational_cost_count',2880),('revenue_eur',916351.47),
        ('operational_cost_eur',230279.65),('gross_profit_eur',686071.82),
        ('budget_eur',3048056.60),('monthly_country_finance_count',60),
        ('route_profitability_count',120),('customer_profitability_count',240),
        ('budget_vs_actual_count',120),('healthy_data_quality_count',38),
        ('retained_data_quality_count',76),('duplicate_invoice_ids',0),
        ('duplicate_cost_ids',0),('duplicate_shipment_ids',0)
    )
    SELECT :P_LOAD_ID,E.CONTROL_NAME,E.EXPECTED_VALUE,A.ACTUAL_VALUE,
      (A.ACTUAL_VALUE-E.EXPECTED_VALUE)::NUMBER(38,2),
      IFF(A.ACTUAL_VALUE=E.EXPECTED_VALUE,'PASS','FAIL')
    FROM EXPECTED E JOIN ACTUAL A USING(CONTROL_NAME);

    IF (EXISTS(SELECT 1 FROM LIBRA.CONTROL.RECONCILIATION_RESULT
               WHERE LOAD_ID=:P_LOAD_ID AND STATUS='FAIL')) THEN
      RETURN 'FAILED_RECONCILIATION';
    END IF;

    UPDATE LIBRA.CONTROL.LOAD_RUN SET STATUS='SUCCEEDED',COMPLETED_AT=CURRENT_TIMESTAMP()
      WHERE LOAD_ID=:P_LOAD_ID;
    RETURN 'SUCCEEDED';
END;
$$;
