CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_DATE AS SELECT * FROM LIBRA.CORE.DIM_DATE;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_COUNTRY AS
SELECT COUNTRY_KEY, COUNTRY_CODE, COUNTRY_NAME, DEFAULT_CURRENCY FROM LIBRA.CORE.DIM_COUNTRY;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_CUSTOMER AS
SELECT CUSTOMER_KEY, CUSTOMER_ID, CUSTOMER_NAME, COUNTRY_KEY FROM LIBRA.CORE.DIM_CUSTOMER;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_ROUTE AS
SELECT ROUTE_KEY, ROUTE_ID, ORIGIN_COUNTRY_KEY, DESTINATION_COUNTRY_KEY, TRANSPORT_MODE,
       DISTANCE_KM, STANDARD_TRANSIT_DAYS FROM LIBRA.CORE.DIM_ROUTE;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_COST_CENTER AS
SELECT COST_CENTER_KEY, COST_CENTER_ID, COST_CENTER_NAME, COUNTRY_KEY
FROM LIBRA.CORE.DIM_COST_CENTER;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DIM_CURRENCY AS
SELECT CURRENCY_KEY, CURRENCY_CODE, CURRENCY_NAME, DECIMAL_PLACES
FROM LIBRA.CORE.DIM_CURRENCY;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.FACT_SHIPMENT AS
SELECT SHIPMENT_ID, SHIPMENT_DATE_KEY, ROUTE_KEY, COUNTRY_KEY, CUSTOMER_KEY,
       COST_CENTER_KEY, CURRENCY_KEY, VOLUME_M3, ORIGINAL_AMOUNT, FX_RATE_TO_EUR,
       AMOUNT_EUR, SOURCE_BATCH_ID, SOURCE_FINGERPRINT, SOURCE_FILE, SOURCE_ROW_NUMBER
FROM LIBRA.CORE.FACT_SHIPMENT;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.FACT_INVOICE AS
SELECT INVOICE_ID, SHIPMENT_ID, INVOICE_DATE_KEY, COUNTRY_KEY, CUSTOMER_KEY,
       ROUTE_KEY, COST_CENTER_KEY, CURRENCY_KEY, ORIGINAL_AMOUNT, FX_RATE_TO_EUR, AMOUNT_EUR,
       AMOUNT_AT_COMPARISON_RATE_EUR, SOURCE_UPDATED_AT, SOURCE_BATCH_ID,
       SOURCE_FINGERPRINT, SOURCE_FILE, SOURCE_ROW_NUMBER
FROM LIBRA.CORE.FACT_INVOICE;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.FACT_OPERATIONAL_COST AS
SELECT COST_ID, SHIPMENT_ID, ROUTE_KEY, CUSTOMER_KEY, COST_CENTER_KEY, COUNTRY_KEY, POSTING_DATE_KEY,
       COST_TYPE, CURRENCY_KEY, ORIGINAL_AMOUNT, FX_RATE_TO_EUR, AMOUNT_EUR,
       SOURCE_BATCH_ID, SOURCE_FINGERPRINT, SOURCE_FILE, SOURCE_ROW_NUMBER
FROM LIBRA.CORE.FACT_OPERATIONAL_COST;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.FACT_BUDGET AS
SELECT MONTH_DATE_KEY, COST_CENTER_KEY, CURRENCY_KEY, ORIGINAL_AMOUNT, FX_RATE_TO_EUR,
       AMOUNT_EUR, SOURCE_BATCH_ID, SOURCE_FINGERPRINT, SOURCE_FILE, SOURCE_ROW_NUMBER
FROM LIBRA.CORE.FACT_BUDGET;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.FACT_DATA_QUALITY_RESULT AS
SELECT * FROM LIBRA.CORE.FACT_DATA_QUALITY_RESULT;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.MONTHLY_COUNTRY_FINANCE AS
WITH REVENUE AS (
  SELECT D.MONTH_START,I.COUNTRY_KEY,SUM(I.AMOUNT_EUR)::NUMBER(20,2) REVENUE_EUR
  FROM LIBRA.CORE.FACT_INVOICE I JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=I.INVOICE_DATE_KEY
  GROUP BY D.MONTH_START,I.COUNTRY_KEY
), COST AS (
  SELECT D.MONTH_START,O.COUNTRY_KEY,SUM(O.AMOUNT_EUR)::NUMBER(20,2) COST_EUR
  FROM LIBRA.CORE.FACT_OPERATIONAL_COST O
  JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=O.POSTING_DATE_KEY
  GROUP BY D.MONTH_START,O.COUNTRY_KEY
), KEYS AS (
  SELECT MONTH_START,COUNTRY_KEY FROM REVENUE UNION
  SELECT MONTH_START,COUNTRY_KEY FROM COST
)
SELECT K.MONTH_START,C.COUNTRY_CODE,COALESCE(R.REVENUE_EUR,0)::NUMBER(20,2) TOTAL_REVENUE_EUR,
       COALESCE(O.COST_EUR,0)::NUMBER(20,2) TOTAL_OPERATIONAL_COST_EUR,
       (COALESCE(R.REVENUE_EUR,0)-COALESCE(O.COST_EUR,0))::NUMBER(20,2) GROSS_PROFIT_EUR
FROM KEYS K JOIN LIBRA.CORE.DIM_COUNTRY C USING(COUNTRY_KEY)
LEFT JOIN REVENUE R USING(MONTH_START,COUNTRY_KEY)
LEFT JOIN COST O USING(MONTH_START,COUNTRY_KEY);
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.ROUTE_PROFITABILITY AS
WITH REVENUE AS (
  SELECT D.MONTH_START,I.ROUTE_KEY,SUM(I.AMOUNT_EUR)::NUMBER(20,2) REVENUE_EUR
  FROM LIBRA.CORE.FACT_INVOICE I JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=I.INVOICE_DATE_KEY
  GROUP BY D.MONTH_START,I.ROUTE_KEY
), COST AS (
  SELECT D.MONTH_START,O.ROUTE_KEY,SUM(O.AMOUNT_EUR)::NUMBER(20,2) COST_EUR
  FROM LIBRA.CORE.FACT_OPERATIONAL_COST O
  JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=O.POSTING_DATE_KEY
  GROUP BY D.MONTH_START,O.ROUTE_KEY
), SHIPMENTS AS (
  SELECT D.MONTH_START,S.ROUTE_KEY,COUNT(DISTINCT S.SHIPMENT_ID) SHIPMENT_COUNT
  FROM LIBRA.CORE.FACT_SHIPMENT S JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=S.SHIPMENT_DATE_KEY
  GROUP BY D.MONTH_START,S.ROUTE_KEY
), KEYS AS (
  SELECT MONTH_START,ROUTE_KEY FROM REVENUE UNION
  SELECT MONTH_START,ROUTE_KEY FROM COST UNION
  SELECT MONTH_START,ROUTE_KEY FROM SHIPMENTS
)
SELECT K.MONTH_START,R.ROUTE_ID,COALESCE(S.SHIPMENT_COUNT,0) SHIPMENT_COUNT,
  COALESCE(I.REVENUE_EUR,0)::NUMBER(20,2) TOTAL_REVENUE_EUR,
  COALESCE(O.COST_EUR,0)::NUMBER(20,2) OPERATIONAL_COST_EUR,
  (COALESCE(I.REVENUE_EUR,0)-COALESCE(O.COST_EUR,0))::NUMBER(20,2) GROSS_PROFIT_EUR
FROM KEYS K JOIN LIBRA.CORE.DIM_ROUTE R USING(ROUTE_KEY)
LEFT JOIN REVENUE I USING(MONTH_START,ROUTE_KEY)
LEFT JOIN COST O USING(MONTH_START,ROUTE_KEY)
LEFT JOIN SHIPMENTS S USING(MONTH_START,ROUTE_KEY);
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.CUSTOMER_PROFITABILITY AS
WITH REVENUE AS (
  SELECT D.MONTH_START,I.CUSTOMER_KEY,SUM(I.AMOUNT_EUR)::NUMBER(20,2) REVENUE_EUR
  FROM LIBRA.CORE.FACT_INVOICE I JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=I.INVOICE_DATE_KEY
  GROUP BY D.MONTH_START,I.CUSTOMER_KEY
), COST AS (
  SELECT D.MONTH_START,O.CUSTOMER_KEY,SUM(O.AMOUNT_EUR)::NUMBER(20,2) COST_EUR
  FROM LIBRA.CORE.FACT_OPERATIONAL_COST O
  JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=O.POSTING_DATE_KEY
  GROUP BY D.MONTH_START,O.CUSTOMER_KEY
), SHIPMENTS AS (
  SELECT D.MONTH_START,S.CUSTOMER_KEY,COUNT(DISTINCT S.SHIPMENT_ID) SHIPMENT_COUNT
  FROM LIBRA.CORE.FACT_SHIPMENT S JOIN LIBRA.CORE.DIM_DATE D ON D.DATE_KEY=S.SHIPMENT_DATE_KEY
  GROUP BY D.MONTH_START,S.CUSTOMER_KEY
), KEYS AS (
  SELECT MONTH_START,CUSTOMER_KEY FROM REVENUE UNION
  SELECT MONTH_START,CUSTOMER_KEY FROM COST UNION
  SELECT MONTH_START,CUSTOMER_KEY FROM SHIPMENTS
)
SELECT K.MONTH_START,C.CUSTOMER_ID,COALESCE(S.SHIPMENT_COUNT,0) SHIPMENT_COUNT,
  COALESCE(I.REVENUE_EUR,0)::NUMBER(20,2) TOTAL_REVENUE_EUR,
  COALESCE(O.COST_EUR,0)::NUMBER(20,2) OPERATIONAL_COST_EUR,
  (COALESCE(I.REVENUE_EUR,0)-COALESCE(O.COST_EUR,0))::NUMBER(20,2) GROSS_PROFIT_EUR
FROM KEYS K JOIN LIBRA.CORE.DIM_CUSTOMER C USING(CUSTOMER_KEY)
LEFT JOIN REVENUE I USING(MONTH_START,CUSTOMER_KEY)
LEFT JOIN COST O USING(MONTH_START,CUSTOMER_KEY)
LEFT JOIN SHIPMENTS S USING(MONTH_START,CUSTOMER_KEY);
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.BUDGET_VS_ACTUAL AS
SELECT B.MONTH_DATE_KEY, B.COST_CENTER_KEY, B.AMOUNT_EUR BUDGET_AMOUNT_EUR,
       COALESCE(SUM(O.AMOUNT_EUR),0)::NUMBER(20,2) ACTUAL_COST_EUR,
       (B.AMOUNT_EUR-COALESCE(SUM(O.AMOUNT_EUR),0))::NUMBER(20,2) VARIANCE_EUR
FROM LIBRA.CORE.FACT_BUDGET B
LEFT JOIN LIBRA.CORE.FACT_OPERATIONAL_COST O
  ON O.COST_CENTER_KEY=B.COST_CENTER_KEY
 AND TO_NUMBER(TO_CHAR(TO_DATE(O.POSTING_DATE_KEY::VARCHAR,'YYYYMMDD'),'YYYYMM01'))=B.MONTH_DATE_KEY
GROUP BY B.MONTH_DATE_KEY,B.COST_CENTER_KEY,B.AMOUNT_EUR;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.DATA_QUALITY_SUMMARY AS
SELECT BATCH_ID,AFFECTED_DATASET,RULE_NAME,VALIDATION_STATUS,FAILURE_REASON,
       FAILED_ROW_COUNT,AFFECTED_FINANCIAL_AMOUNT_EUR,EXECUTION_TIMESTAMP
FROM LIBRA.CORE.FACT_DATA_QUALITY_RESULT;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.REFRESH_STATUS AS
SELECT LOAD_ID,CONTRACT_VERSION,SOURCE_FINGERPRINT,STATUS,STARTED_AT,COMPLETED_AT
FROM LIBRA.CONTROL.LOAD_RUN;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.RECONCILIATION_STATUS AS
SELECT LOAD_ID,CONTROL_NAME,EXPECTED_VALUE,ACTUAL_VALUE,DIFFERENCE,STATUS,CHECKED_AT
FROM LIBRA.CONTROL.RECONCILIATION_RESULT;
-- statement
CREATE OR REPLACE VIEW LIBRA.REPORTING.TRANSACTION_DRILLTHROUGH AS
SELECT I.INVOICE_ID,I.SHIPMENT_ID,I.INVOICE_DATE_KEY,C.COUNTRY_CODE,
       CU.CUSTOMER_ID,CC.COST_CENTER_ID,CY.CURRENCY_CODE,I.ORIGINAL_AMOUNT,
       I.FX_RATE_TO_EUR,I.AMOUNT_EUR,I.SOURCE_BATCH_ID,I.SOURCE_FILE,I.SOURCE_ROW_NUMBER
FROM LIBRA.CORE.FACT_INVOICE I
JOIN LIBRA.CORE.DIM_COUNTRY C ON C.COUNTRY_KEY=I.COUNTRY_KEY
JOIN LIBRA.CORE.DIM_CUSTOMER CU ON CU.CUSTOMER_KEY=I.CUSTOMER_KEY
JOIN LIBRA.CORE.DIM_COST_CENTER CC ON CC.COST_CENTER_KEY=I.COST_CENTER_KEY
JOIN LIBRA.CORE.DIM_CURRENCY CY ON CY.CURRENCY_KEY=I.CURRENCY_KEY;
