GRANT USAGE ON SCHEMA LIBRA.LOAD TO ROLE LIBRA_LOADER;
-- statement
GRANT USAGE ON SCHEMA LIBRA.CONTROL TO ROLE LIBRA_LOADER;
-- statement
GRANT SELECT,INSERT,UPDATE,TRUNCATE ON ALL TABLES IN SCHEMA LIBRA.LOAD TO ROLE LIBRA_LOADER;
-- statement
GRANT SELECT,INSERT,UPDATE ON ALL TABLES IN SCHEMA LIBRA.CONTROL TO ROLE LIBRA_LOADER;
-- statement
GRANT READ,WRITE ON STAGE LIBRA.LOAD.PACKAGE_STAGE TO ROLE LIBRA_LOADER;
-- statement
GRANT USAGE ON PROCEDURE LIBRA.CONTROL.PUBLISH_STAGED_PACKAGE(VARCHAR)
TO ROLE LIBRA_LOADER;
-- statement
GRANT USAGE ON SCHEMA LIBRA.REPORTING TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_DATE TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_COUNTRY TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_CUSTOMER TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_ROUTE TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_COST_CENTER TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DIM_CURRENCY TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.FACT_SHIPMENT TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.FACT_INVOICE TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.FACT_OPERATIONAL_COST TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.FACT_BUDGET TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.MONTHLY_COUNTRY_FINANCE TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.ROUTE_PROFITABILITY TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.CUSTOMER_PROFITABILITY TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.BUDGET_VS_ACTUAL TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.TRANSACTION_DRILLTHROUGH TO ROLE LIBRA_FINANCE_READER;
-- statement
GRANT USAGE ON SCHEMA LIBRA.REPORTING TO ROLE LIBRA_DQ_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.FACT_DATA_QUALITY_RESULT TO ROLE LIBRA_DQ_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.DATA_QUALITY_SUMMARY TO ROLE LIBRA_DQ_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.REFRESH_STATUS TO ROLE LIBRA_DQ_READER;
-- statement
GRANT SELECT ON VIEW LIBRA.REPORTING.RECONCILIATION_STATUS TO ROLE LIBRA_DQ_READER;
